# Generated by Django 4.2.7 on 2023-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=128)),
                ('product', models.CharField(max_length=128)),
                ('updateId', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
