# Generated by Django 4.2.7 on 2023-11-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cve',
            old_name='updateId',
            new_name='updateLink',
        ),
    ]
